scrape_configs:
  - job_name: 'RasukanLSPMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal']
        labels:
          application: 'RasukanLSP'