scrape_configs:
  - job_name: 'RasukanAuthMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:80']
        labels:
          application: 'RasukanLSP'